var json_laikipiajoined1={
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 37.125768, 0.040181 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.316361, 0.417567 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.290862, 0.336484 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.405875, 0.060945 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.585834, 0.118159 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.283247, 0.422106 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.337386, 0.420356 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.373005, 0.149563 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.306919, 0.468784 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.31956, 0.04267 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.266381, 0.43917 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.351672, 0.416727 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.268014, 0.459375 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.549866, 0.097757 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.271505, 0.410267 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.319068, 0.372689 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.286159, 0.449885 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.580759, 0.157739 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.340895, 0.390434 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.354043, 0.445576 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 37.114275, 0.06041 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title not issued" }, "geometry": { "type": "Point", "coordinates": [ 36.326939, 0.446816 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title issued" }, "geometry": { "type": "Point", "coordinates": [ 36.309947, 0.344468 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title issued" }, "geometry": { "type": "Point", "coordinates": [ 36.540192, 0.061828 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Title issued" }, "geometry": { "type": "Point", "coordinates": [ 36.2792, 0.04762 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.34676, 0.05122 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.507667, 0.182352 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.125768, 0.040181 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.064095, 0.004817 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.315324, 0.396405 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.389572, 0.301153 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.962806, -0.026022 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.246485, 0.169976 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.091446, 0.085761 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.091446, 0.085761 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.163756, 0.406754 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.9086, 0.157556 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.917342, 0.125745 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.292401, 0.17637 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.900102, 0.562292 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.142911, 0.094113 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.411592, 0.313997 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.335427, 0.179546 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.335427, 0.179546 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.482741, 0.47274 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.330594, 0.281323 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.46426, 0.487972 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.79135, -0.009967 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.27995, 0.00898 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.29697, 0.0448 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.936048, 0.469614 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.079547, 0.374462 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.673918, -0.062946 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.956576, -0.087336 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.923154, 0.00528 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.63311, 0.35826 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.403682, 0.341288 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.980785, -0.042954 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.395247, 0.47098 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.27093, 0.31428 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.395933, 0.392414 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.367553, 0.402029 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.507766, 0.506899 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.164099, 0.068692 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.164099, 0.068692 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.350984, 0.255435 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.378128, 0.327276 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.313214, 0.294643 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.27815, 0.07887 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.291205, 0.47681 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.808376, -0.097266 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.606419, 0.091356 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.644526, 0.046943 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.873051, -0.108192 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.559077, 0.128839 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.30666, 0.18453 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.918137, -0.04035 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.30412, 0.01652 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.984666, -0.134073 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.984666, -0.134073 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.32899, 0.0481 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.782545, 0.020581 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.010162, 0.486312 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.31103, 0.23161 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.316361, 0.417567 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.341287, 0.029989 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.384883, 0.211653 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.411674, 0.421698 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.49631, 0.215977 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.23904, 0.321361 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.421809, 0.265067 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.368105, 0.227392 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.142363, 0.373024 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.351096, 0.19826 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.184146, 0.407766 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.040088, 0.034392 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.27544, 0.03564 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.441542, 0.546527 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.034902, 0.139412 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.37893, 0.404585 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.932685, -0.06684 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.925459, 0.341983 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.356754, 0.27578 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.07818, 0.024331 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.07818, 0.024331 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.355201, 0.134912 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.293495, 0.310982 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.54629, 0.71326 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.429377, 0.402953 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.49784, 0.275356 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.423149, 0.091813 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.35789, 0.06759 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.378211, 0.226997 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.343322, 0.307493 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.954025, -0.105571 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.60739, 0.34317 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.961915, -0.008019 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.474592, 0.330444 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.56374, 0.33272 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.588389, -0.096869 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.660232, 0.365556 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.338823, 0.464134 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.446012, 0.523586 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.42429, 0.24276 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.42429, 0.24276 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.521354, 0.540402 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.562799, -0.08465 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.222896, 0.088845 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.52003, 0.575981 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.454409, 0.443586 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.403474, 0.495168 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.000077, -0.024438 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.929464, -0.006838 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.427904, 0.450755 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.35855, 0.0356 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.10057, -0.000065 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.115152, 0.113963 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.442081, 0.293415 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.780979, -0.097941 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.057235, 0.076819 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.980039, -0.064585 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.401172, 0.159514 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.705731, -0.012135 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.399652, 0.265313 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.074737, 0.12294 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.649363, 0.241479 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.595398, 0.037003 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.129471, 0.073943 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.491508, 0.257578 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.678922, 0.10478 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.49337, 0.496577 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.082109, 0.006491 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.315414, 0.21902 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.315414, 0.21902 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.259055, 0.479462 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.593291, -0.072465 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.395107, 0.361376 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.731605, 0.045927 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.929482, -0.123113 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.357042, 0.390479 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.956421, 0.506233 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.741416, -0.087523 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.110294, -0.014787 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.07422, 0.020148 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.075339, 0.016114 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.066852, 0.017922 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.133947, 0.111125 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.332501, 0.427877 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.440393, 0.481971 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.422334, 0.37498 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.067186, 0.015267 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.046261, 0.489348 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.523194, 0.099806 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.270196, 0.370932 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.509361, 0.361206 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.361057, 0.035678 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.361057, 0.035678 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.213385, 0.109592 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.660503, -0.100583 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.35563, 0.03456 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.983493, 0.010467 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.060907, 0.057985 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.603883, 0.298606 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.090072, 0.048369 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.630398, -0.094117 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.364381, 0.039048 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.31246, 0.431064 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.846569, -0.078909 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.356294, 0.042298 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.9881, -0.25844 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.114275, 0.06041 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.466487, 0.219882 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.679133, 0.433847 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.491623, 0.536214 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.263169, 0.299318 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.263169, 0.299318 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.248412, 0.310362 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.025147, 0.202533 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.379956, 0.187118 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.941615, 0.281787 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.179762, 0.323926 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.516158, 0.468455 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.813844, -0.068608 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.813844, -0.068608 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.523313, 0.224504 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.070643, 0.023453 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.624143, 0.019917 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.040515, 0.236551 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.47056, 0.148847 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.676097, -0.119806 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.26322, 0.00035 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.535728, 0.266598 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.699251, -0.097697 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.363851, 0.282401 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.703526, -0.047747 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.019143, 0.168981 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.35766, 0.07963 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.383713, 0.436636 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.378518, 0.40519 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.782298, -0.068413 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.206318, 0.073154 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.408069, 0.14229 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.100849, 0.42503 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.458203, 0.272903 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.073728, 0.009648 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.35928, 0.03123 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.646121, -0.025972 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.587117, 0.716565 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.549536, 0.580786 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.026662, -0.012104 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.292611, 0.373401 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.30213, 0.24051 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.12098, 0.092714 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.703803, 0.040777 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.35674, 0.06112 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.861754, -0.130272 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.861757, -0.130272 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.264981, 0.328128 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.067482, 0.028019 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.38899, 0.125169 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.954546, -0.062312 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.954546, -0.062312 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.598835, 0.556637 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.3123, 0.15793 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.57974, 0.36065 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.884564, 0.125295 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 37.173894, 0.090045 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.672313, 0.021893 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.382933, 0.483493 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.97621, -0.019026 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.950296, -0.042665 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.776396, -0.036174 ] } },
{ "type": "Feature", "properties": { "Title_Status": "Not applied for Title" }, "geometry": { "type": "Point", "coordinates": [ 36.572234, -0.072898 ] } }
]
}
